name:                J4HSKL
version:             0.1.0.0
github:              "Arthi-chaud/J4HSKL"
license:             BSD3
author:              "Arthi-chaud"
maintainer:          "arthur.jamet@gmail.com"
copyright:           "2021 Arthi-chaud"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Manage & export JSON data

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  J4HSKL-test:
    main:                Spec.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - J4HSKL
    - directory
    - filepath
    - text
    - HUnit
    - test-framework
    - test-framework-hunit
